main/main/urls.py

from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tasks.urls'))
]

main/tasks/urls.py
from django.urls import path, include
from .views import task_list,TaskApi
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'task', TaskApi)

urlpatterns = [
    path('', task_list, name='main'),
    path('api/', include(router.urls)),

]

main/tasks/models.py
from django.db import models


class Task(models.Model):
    name = models.CharField(max_length=10)  # Исправлено
    description = models.CharField(max_length=100)  # Исправлено
    ADD = 'Добавлено'
    WORK = 'В работе'
    READY = 'Выполнено'
    STATUS = [
        (ADD, 'Добавлено'),
        (WORK, 'В работе'),
        (READY, 'Выполнено'),
    ]

    level = models.CharField(max_length=10, choices=STATUS, default=ADD)  # Добавлено поле уровня

    def __str__(self):
        return self.name

main/tasks/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'level']

main/tasks/views.py
from rest_framework import viewsets

from .models import Task
from .serializers import TaskSerializers
from django.shortcuts import render

def task_list(request):
    tasks = Task.objects.all()
    return render(request, 'task_list.html', {'tasks': tasks})

# ТУТ АПИ
class TaskApi(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializers


main/templates/task_list.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Список задач</title>
</head>
<body>
    <h1>Список задач</h1>
    <table>
        <tr>
            <th>Имя</th>
            <th>Описание</th>
            <th>Статус</th>
        </tr>
        {% for task in tasks %}
        <tr>
            <td>{{ task.name }}</td>
            <td>{{ task.description }}</td>
            <td> {{task.get_level_display}}</td>
            </td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>